const inquirer = require('inquirer');

module.exports = {
  ask: async (appName) => {
    const questions = [
      {
        name: 'projectType',
        type: 'list',
        message: 'Project type',
        choices: ['nextjs', 'node', 'python'],
        default: 'nextjs'
      },
      {
        name: 'language',
        type: 'list',
        message: 'Language / Variant',
        choices: ['js', 'ts'],
        default: 'js'
      },
      {
        name: 'includeDocker',
        type: 'confirm',
        message: 'Include Dockerfile?',
        default: true
      },
      {
        name: 'includeCI',
        type: 'confirm',
        message: 'Include CI workflow?',
        default: true
      },
      {
        name: 'description',
        type: 'input',
        message: 'Short description',
        default: `${appName} generated by DevHubTools`
      }
    ];

    const answers = await inquirer.prompt(questions);
    answers.name = appName;
    answers.isNext = answers.projectType === 'nextjs';
    answers.isNode = answers.projectType === 'node';
    answers.isPython = answers.projectType === 'python';
    return answers;
  }
};
